import turtle

# initiate turtle instance
penrose_steps = turtle.Turtle()

# draw it all
penrose_steps.penup()
penrose_steps.pen(shown=False)
penrose_steps.screen.setup(width=.7, height=.7, startx=None, starty=None)
penrose_steps.pensize(width=1)
penrose_steps.speed(10)
penrose_steps.setposition(333, 120)
penrose_steps.pendown()
top_right_corner = penrose_steps.position()
penrose_steps.fillcolor('#404040')
penrose_steps.begin_fill()
penrose_steps.seth(206)
penrose_steps.pendown()
penrose_steps.forward(80)
penrose_steps.seth(90)
penrose_steps.forward(16)
step_2_top_left_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(85)
penrose_steps.seth(90)
penrose_steps.forward(16)
step_3_top_left_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(83)
penrose_steps.seth(90)
penrose_steps.forward(16)
step_4_top_left_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(81)
penrose_steps.seth(90)
penrose_steps.forward(14)
step_5_top_left_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(83)
penrose_steps.seth(90)
penrose_steps.forward(16)
step_6_top_left_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(83)
top_center_position = penrose_steps.position()
penrose_steps.seth(270)
penrose_steps.forward(225)
bottom_center_position = penrose_steps.position()
penrose_steps.seth(28.3)
penrose_steps.forward(499)
penrose_steps.setposition(top_right_corner)
penrose_steps.end_fill()
penrose_steps.penup()
penrose_steps.setposition(step_2_top_left_position)
penrose_steps.pendown()
penrose_steps.seth(155)
penrose_steps.forward(83)
penrose_steps.seth(205)
penrose_steps.forward(67)
step_3_bottom_back_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(15)
step_3_back_position = penrose_steps.position()
penrose_steps.setposition(step_3_top_left_position)
penrose_steps.setposition(step_3_back_position)
penrose_steps.seth(205)
penrose_steps.forward(63)
step_4_bottom_back_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(20)
step_4_back_position = penrose_steps.position()
penrose_steps.setposition(step_4_top_left_position)
penrose_steps.setposition(step_4_back_position)
penrose_steps.seth(207)
penrose_steps.forward(64)
step_5_bottom_back_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(20)
step_5_back_position = penrose_steps.position()
penrose_steps.setposition(step_5_top_left_position)
penrose_steps.setposition(step_5_back_position)
penrose_steps.seth(208)
penrose_steps.forward(65)
step_6_bottom_back_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(20)
step_6_back_position = penrose_steps.position()
penrose_steps.setposition(step_6_top_left_position)
penrose_steps.setposition(step_6_back_position)
penrose_steps.seth(90)
penrose_steps.forward(15)
step_7_top_front_right_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(82)
step_8_bottom_front_right_position = penrose_steps.position()
penrose_steps.seth(90)
penrose_steps.forward(13)
step_8_top_front_right_position = penrose_steps.position()
penrose_steps.penup()
penrose_steps.setposition(top_center_position)
penrose_steps.begin_fill()
penrose_steps.pendown()
penrose_steps.seth(154)
penrose_steps.forward(80)
stair_7_bottom_left_position = penrose_steps.position()
penrose_steps.seth(90)
penrose_steps.forward(15)
step_7_top_front_left_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(84)
step_8_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(90)
penrose_steps.forward(14)
step_8_top_front_left_position = penrose_steps.position()
penrose_steps.seth(155)
penrose_steps.forward(82)
step_8_top_back_left_position = penrose_steps.position()
penrose_steps.seth(271.2)
penrose_steps.forward(230)
penrose_steps.setposition(bottom_center_position)
penrose_steps.setposition(top_center_position)
penrose_steps.end_fill()
penrose_steps.penup()
penrose_steps.setposition(stair_7_bottom_left_position)
penrose_steps.pendown()
penrose_steps.begin_fill()
penrose_steps.setposition(step_6_back_position)
penrose_steps.setposition(step_7_top_front_right_position)
penrose_steps.setposition(step_7_top_front_left_position)
penrose_steps.setposition(stair_7_bottom_left_position)
penrose_steps.end_fill()
penrose_steps.penup()
penrose_steps.setposition(step_8_bottom_front_left_position)
penrose_steps.pendown()
penrose_steps.begin_fill()
penrose_steps.setposition(step_8_bottom_front_right_position)
penrose_steps.setposition(step_8_top_front_right_position)
penrose_steps.setposition(step_8_top_front_left_position)
penrose_steps.setposition(step_8_bottom_front_left_position)
penrose_steps.end_fill()

penrose_steps.penup()
penrose_steps.setposition(step_8_top_back_left_position)
penrose_steps.seth(25)
penrose_steps.pendown()
penrose_steps.forward(82)
step_9_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(90)
penrose_steps.forward(18)
step_9_top_front_left_position = penrose_steps.position()
penrose_steps.seth(26)
penrose_steps.forward(81)
step_10_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(90)
penrose_steps.forward(15)
step_10_top_front_left_position = penrose_steps.position()
penrose_steps.seth(25)
penrose_steps.forward(80)
back_corner = penrose_steps.position()
penrose_steps.seth(335)
penrose_steps.forward(65)
step_11_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(28.3)
penrose_steps.forward(18)
step_11_top_front_left_position = penrose_steps.position()
penrose_steps.seth(334)
penrose_steps.forward(65)
step_12_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(26)
penrose_steps.forward(20)
step_12_top_front_left_position = penrose_steps.position()
penrose_steps.seth(334)
penrose_steps.forward(65)
step_13_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(28)
penrose_steps.forward(19)
step_13_top_front_left_position = penrose_steps.position()
penrose_steps.seth(335)
penrose_steps.forward(62)
step_14_bottom_front_left_position = penrose_steps.position()
penrose_steps.seth(28)
penrose_steps.forward(16)
step_14_top_front_left_position = penrose_steps.position()
penrose_steps.seth(337)
penrose_steps.forward(70)
step_1_bottom_back_left_position = penrose_steps.position()
penrose_steps.seth(28)
penrose_steps.forward(16)
step_1_top_front_left_position = penrose_steps.position()
penrose_steps.setposition(top_right_corner)

penrose_steps.penup()
penrose_steps.setposition(step_11_bottom_front_left_position)
penrose_steps.pendown()
penrose_steps.seth(205)
penrose_steps.forward(61)
step_11_top_front_right_position = penrose_steps.position()
penrose_steps.begin_fill()
penrose_steps.seth(270)
penrose_steps.forward(17)
step_11_bottom_front_right_position = penrose_steps.position()
penrose_steps.setposition(step_10_top_front_left_position)
penrose_steps.setposition(step_10_bottom_front_left_position)
penrose_steps.seth(335)
penrose_steps.forward(80)
step_10_bottom_front_center_position = penrose_steps.position()
penrose_steps.seth(206)
penrose_steps.forward(82)
step_9_top_front_right_position = penrose_steps.position()
penrose_steps.setposition(step_9_top_front_left_position)
penrose_steps.setposition(step_9_bottom_front_left_position)
penrose_steps.setposition(step_8_top_front_right_position)
penrose_steps.setposition(step_8_bottom_front_right_position)
penrose_steps.setposition(step_7_top_front_right_position)
penrose_steps.setposition(step_6_back_position)
penrose_steps.setposition(step_6_bottom_back_position)
penrose_steps.setposition(step_5_back_position)
penrose_steps.setposition(step_5_bottom_back_position)
penrose_steps.setposition(step_4_back_position)
penrose_steps.setposition(step_4_bottom_back_position)
penrose_steps.setposition(step_3_back_position)
penrose_steps.setposition(step_3_bottom_back_position)
penrose_steps.seth(26)
penrose_steps.forward(25)
inner_corner_top_right_position = penrose_steps.position()
penrose_steps.seth(152)
penrose_steps.forward(40)
step_14_top_front_right_position = penrose_steps.position()
penrose_steps.seth(270)
penrose_steps.forward(15)
step_14_bottom_front_right_position = penrose_steps.position()
penrose_steps.seth(156)
penrose_steps.forward(82)
step_13_top_front_right_position = penrose_steps.position()
penrose_steps.seth(265)
penrose_steps.forward(15)
step_13_bottom_front_right_position = penrose_steps.position()
penrose_steps.seth(154)
penrose_steps.forward(82)
step_12_top_front_right_position = penrose_steps.position()
penrose_steps.seth(265)
penrose_steps.forward(15)
step_12_bottom_front_right_position = penrose_steps.position()
penrose_steps.setposition(step_11_top_front_right_position)
penrose_steps.end_fill()
penrose_steps.penup()
penrose_steps.setposition(step_9_top_front_right_position)
penrose_steps.pendown()
penrose_steps.setposition(step_8_top_front_right_position)
penrose_steps.penup()
penrose_steps.setposition(step_11_bottom_front_right_position)
penrose_steps.pendown()
penrose_steps.setposition(step_10_bottom_front_center_position)
penrose_steps.setposition(step_6_back_position)
penrose_steps.penup()
penrose_steps.setposition(step_1_top_front_left_position)
penrose_steps.pendown()
penrose_steps.seth(206)
penrose_steps.forward(62)
penrose_steps.penup()
penrose_steps.setposition(step_14_top_front_left_position)
penrose_steps.pendown()
penrose_steps.setposition(step_14_top_front_right_position)
penrose_steps.penup()
penrose_steps.setposition(step_13_top_front_left_position)
penrose_steps.pendown()
penrose_steps.setposition(step_13_top_front_right_position)
penrose_steps.penup()
penrose_steps.setposition(step_12_top_front_left_position)
penrose_steps.pendown()
penrose_steps.setposition(step_12_top_front_right_position)
penrose_steps.speed(1)
penrose_steps.penup()
penrose_steps.setposition((-30,280))
penrose_steps.write(arg='How Far Will You Climb?', align="center", font=("Comic Sans MS", 20, "normal"))

penrose_steps.speed(1)
penrose_steps.shape("turtle")
penrose_steps.color('green')
penrose_steps.showturtle()
penrose_steps.shapesize(1.6,1.6,4)
print(top_right_corner)
penrose_steps.seth(215)
penrose_steps.setposition((270,130))
penrose_steps.seth(190)
penrose_steps.seth(240)
penrose_steps.seth(190)
penrose_steps.seth(240)
penrose_steps.seth(190)
penrose_steps.seth(240)
penrose_steps.seth(0)
penrose_steps.seth(140)
penrose_steps.seth(215)


# penrose_steps.tiltangle(10)

# penrose_steps.speed(1)
# penrose_steps.pen(shown=True)

# all done!
turtle.done()
